### PR TITLE
Integration Tests Code Coverage Support

### PR DESCRIPTION
**Pull request by frincon**
This patch add the possibility to create Metrics for Integration Tests.

### CODE REVIEW

**Comment by sandermvanvliet** [comment]
@dbolkensteyn any update on when this is going to be released?

**Comment by dbolkensteyn** [comment]
no update yet @sandermvanvliet - however you can deploy a snapshot version of the plugin with this pull request if you need this urgently.

**Comment by Austin-Chadwick** [comment]
Asking again... sorry if this is redundant...
@dbolkensteyn any update on when this is going to be released? 
Thanks!

**Comment by Austin-Chadwick** [comment]
@dbolkensteyn
If not any time soon? Can you give a step by step on how to "deploy a snapshot version of the plugin with this pull request" for a newbie? Thanks!

**Comment by jabbera** [comment]
@dbolkensteyn 

Is this likely to merged as is? I don't want to deploy a snapshot release to find that it breaks when the "real" implementation comes out.

**Comment by dbolkensteyn** [comment]
Hi @jabbera - I can't make any promise

**Comment by LastManStanding** [comment]
@dbolkensteyn , is there any timeline for the release /inclusion of this feature? If not what needs to be done ? Thanks

**Comment by sonicflare** [comment]
anyone?

**Comment by asbrown77** [comment]
History comments suggest that a release for this feature was going to happen 8 months ago but has gone all quiet since. Is there any update? What's needed to get this released?

**Comment by jabbera** [comment]
It's currently scheduled for the next release on 2/29: https://jira.sonarsource.com/browse/SONARNTEST/fixforversion/11677

lets hope it stays there!

**Comment by dbolkensteyn** [comment]
Thanks again @frincon , I've rebased the PR and slightly adapted it into #25 - I'm therefore closing this one

**Pull request closed without merging**
